### ISSUE TITLE
less-important issue: county pop density 2018 data errors for Virginia and DC

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/handsondataviz-maps#2]
@ilyankou - this is a less-important issue, but please fix when you have time

The county pop density geojson map you created from ACS 2018 5-year data is very good, but noticed some errors when using it in the East Coast Greenway demo for Leaflet Map with Google Sheets. I pasted your email notes into a README file for this folder.

1) In Virginia, there are overlapping entries for several counties with large population centers. See screenshot of Charlottesville (a city) inside Albemarle County. In most cases these locations are named differently, but in at least one case, they are the same: Bedford (a city) inside Bedford County, VA.

2) Lacks pop density data entry for Washington DC, probably because it's not a state or a county, and did not appear in regular US census data on states & counties.

thanks!

![image](https://user-images.githubusercontent.com/649719/103588127-8c500180-4eb6-11eb-9793-04c6fc696b24.png)

**Comment by ilyankou** [comment]
Charlottesville looks like an independent city = county-like entity, see [this Wikipedia article](https://en.wikipedia.org/wiki/Charlottesville%2C_Virginia) and notice how calculated density is nearly identical! None of the polygons are overlaying each other. I merged them with their GeoID which should be unique per geography.

I can create & insert a polygon for DC – stay tuned.

**Comment by JackDougherty** [comment]
Wow, I had no idea that cities and counties were independent of each other in VA. Thanks for correcting my error!
[https://en.wikipedia.org/wiki/List_of_cities_and_counties_in_Virginia](https://en.wikipedia.org/wiki/List_of_cities_and_counties_in_Virginia)
The Commonwealth of Virginia is divided into 95 counties, along with 38 independent cities that are considered county-equivalents for census purposes.

**Comment by JackDougherty** [comment]
Please make sure Bedford (city) has pop density data, since it was an empty field in the previous file you created, which threw an NaN error in Leaflet and led me down this rabbit hole...
